[pytest]
pythonpath = . app
asyncio_mode = auto
python_files = *_test.py *_tests.py test_*.py

filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning
